trigger:
  branches:
   include:
     - UI_Changes


variables:
    buildPlatform: 'x86'
    imageName: 'windows-latest'
    artifactName: 'Ideploy-drop'
    mavenOption: '-Xmx3072m'
    goals : 'package'
    jdkVersion: '1.14'
    pomPath: 'test1'
    contentsPath: '**/target/*.jar'
    testResultPath: ''

pool:
    vmImage: '$(imageName)'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: '$(pomPath)'
    mavenOptions: '$(mavenOption)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '$(jdkVersion)'
    jdkArchitectureOption: '$(buildPlatform)'
    publishJUnitResults: false
    
    goals: '$(goals)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '$(contentsPath)'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: '$(artifactName)'

